'use client'

import { useState } from 'react'
import Link from 'next/link'
import { Button } from '@/components/ui/Button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/Card'
import { 
  ChevronDown, 
  ChevronUp, 
  Search, 
  HelpCircle,
  ArrowLeft,
  MessageCircle,
  Mail,
  Phone
} from 'lucide-react'
import { Navbar } from '@/components/Navbar'
import { Footer } from '@/components/Footer'

export default function FAQPage() {
  const [searchTerm, setSearchTerm] = useState('')
  const [expandedItems, setExpandedItems] = useState({})

  const faqCategories = [
    {
      title: 'Getting Started',
      icon: <HelpCircle className="h-5 w-5" />,
      questions: [
        {
          question: 'What is Carbonease?',
          answer: 'Carbonease is a leading carbon credit trading platform that connects buyers and sellers of verified carbon credits. We make it easy for individuals and organizations to purchase carbon credits to offset their emissions and support renewable energy projects worldwide.'
        },
        {
          question: 'How do I create an account?',
          answer: 'Creating an account is simple! Click the "Get Started" button on our homepage, fill out the registration form with your details, choose whether you want to be a buyer or seller, and verify your email address. You\'ll be ready to start trading carbon credits in minutes.'
        },
        {
          question: 'What\'s the difference between buyers and sellers?',
          answer: 'Buyers purchase carbon credits to offset their emissions and support environmental projects. Sellers list their carbon credits for sale on our platform. You can choose your role during registration, and you can always change it later in your account settings.'
        },
        {
          question: 'Are there any fees?',
          answer: 'We charge a small transaction fee on successful trades to maintain our platform and ensure quality service. The exact fee structure is transparent and displayed before you complete any transaction. There are no hidden fees or monthly subscriptions.'
        }
      ]
    },
    {
      title: 'Carbon Credits',
      icon: <MessageCircle className="h-5 w-5" />,
      questions: [
        {
          question: 'What are carbon credits?',
          answer: 'Carbon credits are certificates that represent the reduction or removal of one tonne of CO₂ from the atmosphere. They are generated by renewable energy projects, reforestation efforts, and other climate-positive activities that have been verified by international standards.'
        },
        {
          question: 'How do I know the credits are legitimate?',
          answer: 'All carbon credits on our platform are verified by internationally recognized standards such as VCS, Gold Standard, and CAR. Each credit comes with detailed documentation, certification information, and project details. We also conduct our own verification process before listing any credits.'
        },
        {
          question: 'What types of projects generate carbon credits?',
          answer: 'Carbon credits come from various renewable energy projects including solar farms, wind farms, hydroelectric plants, geothermal energy, biomass projects, and reforestation efforts. Each project type is clearly labeled and includes detailed information about its environmental impact.'
        },
        {
          question: 'How long are carbon credits valid?',
          answer: 'Carbon credits are typically valid for the vintage year they were generated and can be used to offset emissions for that specific year. The validity period depends on the certification standard and project type, which is clearly indicated for each credit listing.'
        }
      ]
    },
    {
      title: 'Buying Credits',
      icon: <ChevronDown className="h-5 w-5" />,
      questions: [
        {
          question: 'How do I purchase carbon credits?',
          answer: 'Browse our marketplace to find credits that match your needs, use filters to narrow down by energy type, location, or certification. Click on a credit to view details, select the quantity you want, and proceed to checkout. Payment is processed securely through Stripe.'
        },
        {
          question: 'What payment methods do you accept?',
          answer: 'We accept all major credit cards (Visa, Mastercard, American Express) and digital wallets through our secure Stripe payment processor. All payments are encrypted and processed securely.'
        },
        {
          question: 'When will I receive my certificate?',
          answer: 'Once your payment is confirmed and the transaction is completed, you\'ll receive a digital certificate within 24 hours. You can download it from your dashboard and use it for reporting or compliance purposes.'
        },
        {
          question: 'Can I get a refund?',
          answer: 'We offer refunds within 30 days of purchase if you\'re not satisfied with your carbon credits. However, once a certificate has been issued and used for reporting, refunds may not be possible. Contact our support team for assistance.'
        }
      ]
    },
    {
      title: 'Selling Credits',
      icon: <ChevronUp className="h-5 w-5" />,
      questions: [
        {
          question: 'How do I list my carbon credits for sale?',
          answer: 'First, ensure you have a seller account. Then go to your dashboard and click "List New Credits." Fill out the project details, upload verification documents, set your price, and submit for review. Our team will verify the information before listing.'
        },
        {
          question: 'What documents do I need to provide?',
          answer: 'You\'ll need to provide project documentation, certification certificates, verification reports, and any other relevant documents that prove the legitimacy of your carbon credits. All documents should be in PDF format.'
        },
        {
          question: 'How do I set the right price?',
          answer: 'Research similar credits on our platform to understand market rates. Consider factors like project type, certification standard, vintage year, and location. You can always adjust your prices after listing.'
        },
        {
          question: 'When do I get paid?',
          answer: 'Payments are processed after a successful sale and are typically deposited into your account within 3-5 business days, minus our platform fee. You can track all transactions in your seller dashboard.'
        }
      ]
    },
    {
      title: 'Account & Security',
      icon: <HelpCircle className="h-5 w-5" />,
      questions: [
        {
          question: 'How do I reset my password?',
          answer: 'Click "Forgot Password" on the login page, enter your email address, and we\'ll send you a secure reset link. Follow the instructions in the email to create a new password.'
        },
        {
          question: 'Is my personal information secure?',
          answer: 'Yes, we use industry-standard encryption and security measures to protect your data. We never share your personal information with third parties without your consent, and all transactions are processed securely.'
        },
        {
          question: 'Can I change my account type?',
          answer: 'Yes, you can change between buyer and seller accounts in your account settings. Note that changing your account type may affect your dashboard and available features.'
        },
        {
          question: 'How do I delete my account?',
          answer: 'You can delete your account from the security section in your account settings. This action is irreversible and will remove all your data from our platform. Make sure to download any important certificates before deletion.'
        }
      ]
    }
  ]

  const filteredCategories = faqCategories.map(category => ({
    ...category,
    questions: category.questions.filter(q => 
      q.question.toLowerCase().includes(searchTerm.toLowerCase()) ||
      q.answer.toLowerCase().includes(searchTerm.toLowerCase())
    )
  })).filter(category => category.questions.length > 0)

  const toggleExpanded = (categoryIndex, questionIndex) => {
    const key = `${categoryIndex}-${questionIndex}`
    setExpandedItems(prev => ({
      ...prev,
      [key]: !prev[key]
    }))
  }

  return (
    <div className="min-h-screen bg-background">
      <Navbar />
      
      {/* Hero Section */}
      <section className="relative overflow-hidden bg-gradient-to-br from-green-50 to-blue-50">
        <div className="absolute inset-0 bg-grid-pattern opacity-5"></div>
        <div className="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-24">
          <div className="text-center">
            <h1 className="text-4xl md:text-6xl font-bold text-gray-900 mb-6">
              Frequently Asked
              <span className="gradient-text block">Questions</span>
            </h1>
            <p className="text-xl text-gray-600 mb-8 max-w-3xl mx-auto">
              Find answers to common questions about carbon credit trading, our platform, and how to get started.
            </p>
          </div>
        </div>
      </section>

      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
        {/* Search */}
        <div className="mb-8">
          <div className="relative">
            <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 h-5 w-5 text-gray-400" />
            <input
              type="text"
              placeholder="Search FAQ..."
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              className="w-full pl-10 pr-4 py-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-green-500 focus:border-transparent"
            />
          </div>
        </div>

        {/* FAQ Categories */}
        <div className="space-y-8">
          {filteredCategories.map((category, categoryIndex) => (
            <Card key={categoryIndex}>
              <CardHeader>
                <CardTitle className="flex items-center">
                  {category.icon}
                  <span className="ml-2">{category.title}</span>
                </CardTitle>
              </CardHeader>
              <CardContent>
                <div className="space-y-4">
                  {category.questions.map((item, questionIndex) => {
                    const key = `${categoryIndex}-${questionIndex}`
                    const isExpanded = expandedItems[key]
                    
                    return (
                      <div key={questionIndex} className="border-b last:border-b-0 pb-4 last:pb-0">
                        <button
                          onClick={() => toggleExpanded(categoryIndex, questionIndex)}
                          className="w-full text-left flex items-center justify-between py-2 hover:text-green-600 transition-colors"
                        >
                          <h3 className="font-medium text-lg">{item.question}</h3>
                          {isExpanded ? (
                            <ChevronUp className="h-5 w-5" />
                          ) : (
                            <ChevronDown className="h-5 w-5" />
                          )}
                        </button>
                        {isExpanded && (
                          <div className="mt-3 text-gray-600 leading-relaxed">
                            {item.answer}
                          </div>
                        )}
                      </div>
                    )
                  })}
                </div>
              </CardContent>
            </Card>
          ))}
        </div>

        {/* No Results */}
        {filteredCategories.length === 0 && searchTerm && (
          <Card>
            <CardContent className="p-12 text-center">
              <HelpCircle className="h-12 w-12 text-gray-400 mx-auto mb-4" />
              <h3 className="text-lg font-medium text-gray-900 mb-2">
                No results found
              </h3>
              <p className="text-gray-600 mb-4">
                We couldn't find any FAQ items matching "{searchTerm}". Try different keywords or contact our support team.
              </p>
              <Button onClick={() => setSearchTerm('')}>
                Clear Search
              </Button>
            </CardContent>
          </Card>
        )}

        {/* Contact Support */}
        <Card className="mt-12">
          <CardHeader>
            <CardTitle>Still have questions?</CardTitle>
            <CardDescription>
              Can't find what you're looking for? Our support team is here to help.
            </CardDescription>
          </CardHeader>
          <CardContent>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
              <div className="text-center">
                <div className="w-12 h-12 bg-green-100 rounded-full flex items-center justify-center mx-auto mb-3">
                  <Mail className="h-6 w-6 text-green-600" />
                </div>
                <h4 className="font-medium mb-2">Email Support</h4>
                <p className="text-sm text-gray-600 mb-3">
                  Get help via email within 24 hours
                </p>
                <Link href="mailto:support@carbonease.com">
                  <Button variant="outline" size="sm">
                    Email Us
                  </Button>
                </Link>
              </div>
              
              <div className="text-center">
                <div className="w-12 h-12 bg-blue-100 rounded-full flex items-center justify-center mx-auto mb-3">
                  <Phone className="h-6 w-6 text-blue-600" />
                </div>
                <h4 className="font-medium mb-2">Phone Support</h4>
                <p className="text-sm text-gray-600 mb-3">
                  Call us during business hours
                </p>
                <Link href="tel:+15551234567">
                  <Button variant="outline" size="sm">
                    Call Us
                  </Button>
                </Link>
              </div>
              
              <div className="text-center">
                <div className="w-12 h-12 bg-purple-100 rounded-full flex items-center justify-center mx-auto mb-3">
                  <MessageCircle className="h-6 w-6 text-purple-600" />
                </div>
                <h4 className="font-medium mb-2">Live Chat</h4>
                <p className="text-sm text-gray-600 mb-3">
                  Chat with our support team
                </p>
                <Link href="/contact">
                  <Button variant="outline" size="sm">
                    Start Chat
                  </Button>
                </Link>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>

      <Footer />
    </div>
  )
}
